### ISSUE TITLE
is this a functional code?

### ISSUE THREAD

**Issue by Bashar** [jrocharodrigues/sipamos#1]
I saw your stackoverflow question and was wondering if you managed to get this code working?

because i'm unable to connect to my SIP provider to make the call

**Comment by jrocharodrigues** [comment]
Hi,

Yes this works. I use it daily with my provider.
Your provider probably needs different settings for connection

**Comment by Bashar** [comment]
Hi @jrocharodrigues 
Yes I updated `pjsua.AccountConfig` part, but seems not working, i don't have acc_cfg.proxy so i commented it out, could it be the problem?

**Comment by Bashar** [comment]
I managed to connect to my SIP provider (had full username, removed the @ part and worked)

but after sending Registration, it doesn't ring/call the destination, from stdout shows lines line this:
14:23:21.341            pjsua_aud.c  Closing sound device after idle for 1 second(s)
14:23:21.341            pjsua_aud.c  .Closing null sound device..
